package prompt

import (
	"fmt"
	"strings"
)

// Theme controls what components are shown in the prompt.
type Theme string

const (
	ThemeMinimal Theme = "minimal" // git only
	ThemeFull    Theme = "full"    // git + k8s
)

// Options configures prompt generation.
type Options struct {
	Theme Theme
	NoK8s bool
}

// GenerateScript returns a bash script that sets PS1 with git branch and optional k8s context.
func GenerateScript(opts Options) string {
	var b strings.Builder

	b.WriteString(scriptHeader)
	b.WriteString(gitBranchFunc)

	showK8s := opts.Theme == ThemeFull && !opts.NoK8s
	if showK8s {
		b.WriteString(k8sContextFunc)
	}

	b.WriteString(buildPS1(showK8s))
	b.WriteString(scriptFooter)

	return b.String()
}

// ShowComponents returns a summary of the current environment for preview.
func ShowComponents(opts Options) []Component {
	var components []Component

	components = append(components, Component{
		Name:  "user@host",
		Value: getCurrentUser(),
	})

	components = append(components, Component{
		Name:  "directory",
		Value: getCurrentDir(),
	})

	if branch := getGitBranch(); branch != "" {
		dirty := ""
		if isGitDirty() {
			dirty = " *"
		}
		components = append(components, Component{
			Name:  "git",
			Value: branch + dirty,
		})
	}

	showK8s := opts.Theme == ThemeFull && !opts.NoK8s
	if showK8s {
		if ctx := getK8sContext(); ctx != "" {
			components = append(components, Component{
				Name:  "k8s",
				Value: ctx,
			})
		}
	}

	return components
}

// Component represents a single prompt element.
type Component struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// FormatPreview renders components as a human-readable preview.
func FormatPreview(components []Component) string {
	var b strings.Builder
	for _, c := range components {
		b.WriteString(fmt.Sprintf("  %-12s %s\n", c.Name+":", c.Value))
	}
	return b.String()
}

func buildPS1(showK8s bool) string {
	var b strings.Builder

	b.WriteString("\n# Build PS1\n")
	b.WriteString("__bp_prompt() {\n")
	b.WriteString("  local exit_code=$?\n")
	b.WriteString("  local reset='\\[\\033[0m\\]'\n")
	b.WriteString("  local red='\\[\\033[31m\\]'\n")
	b.WriteString("  local green='\\[\\033[32m\\]'\n")
	b.WriteString("  local yellow='\\[\\033[33m\\]'\n")
	b.WriteString("  local blue='\\[\\033[34m\\]'\n")
	b.WriteString("  local cyan='\\[\\033[36m\\]'\n")
	b.WriteString("  local bold='\\[\\033[1m\\]'\n")
	b.WriteString("\n")
	b.WriteString("  # Exit code indicator\n")
	b.WriteString("  local indicator\n")
	b.WriteString("  if [ $exit_code -eq 0 ]; then\n")
	b.WriteString("    indicator=\"${green}❯${reset}\"\n")
	b.WriteString("  else\n")
	b.WriteString("    indicator=\"${red}❯${reset}\"\n")
	b.WriteString("  fi\n")
	b.WriteString("\n")
	b.WriteString("  # Git branch\n")
	b.WriteString("  local git_info\n")
	b.WriteString("  git_info=$(__bp_git_branch)\n")
	b.WriteString("  if [ -n \"$git_info\" ]; then\n")
	b.WriteString("    git_info=\" ${yellow}(${git_info})${reset}\"\n")
	b.WriteString("  fi\n")

	if showK8s {
		b.WriteString("\n")
		b.WriteString("  # K8s context\n")
		b.WriteString("  local k8s_info\n")
		b.WriteString("  k8s_info=$(__bp_k8s_context)\n")
		b.WriteString("  if [ -n \"$k8s_info\" ]; then\n")
		b.WriteString("    k8s_info=\" ${cyan}[${k8s_info}]${reset}\"\n")
		b.WriteString("  fi\n")
	}

	b.WriteString("\n")
	b.WriteString("  PS1=\"${bold}${blue}\\u@\\h${reset} ${green}\\w${reset}")
	if showK8s {
		b.WriteString("${k8s_info}")
	}
	b.WriteString("${git_info} ${indicator} \"\n")
	b.WriteString("}\n")
	b.WriteString("\nPROMPT_COMMAND=__bp_prompt\n")

	return b.String()
}

const scriptHeader = `#!/usr/bin/env bash
# bash-pilot prompt — generated by 'bash-pilot prompt init'
# Add to your ~/.bashrc or ~/.bash_profile:
#   eval "$(bash-pilot prompt init)"

`

const gitBranchFunc = `# Git branch with dirty indicator
__bp_git_branch() {
  local branch
  branch=$(git symbolic-ref --short HEAD 2>/dev/null || git describe --tags --exact-match 2>/dev/null)
  if [ -n "$branch" ]; then
    local dirty=""
    if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
      dirty=" *"
    fi
    printf '%s%s' "$branch" "$dirty"
  fi
}
`

const k8sContextFunc = `# Kubernetes context:namespace
__bp_k8s_context() {
  command -v kubectl &>/dev/null || return
  local ctx ns
  ctx=$(kubectl config current-context 2>/dev/null) || return
  ns=$(kubectl config view --minify --output 'jsonpath={..namespace}' 2>/dev/null)
  if [ -n "$ns" ] && [ "$ns" != "default" ]; then
    printf '%s:%s' "$ctx" "$ns"
  else
    printf '%s' "$ctx"
  fi
}
`

const scriptFooter = ""
